services:
  streamui-web-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: litenvr-web
    container_name: litenvr-web-server
    command: "bash start.sh"
    network_mode: "host"
    volumes:
      - ../:/workspace
      - /opt/media/bin/www/record:/opt/media/bin/www/record
      - /opt/media/conf:/opt/media/conf
    restart: unless-stopped
    depends_on:
      - zlm-server

  zlm-server:
    image: zlmediakit/zlmediakit:master
    container_name: zlm-server
    ports:
      - "1935:1935"
      - "8080:80"
      - "8443:443"
      - "8554:554"
      - "10000:10000"
      - "10000:10000/udp"
      - "8000:8000/udp"
      - "9000:9000/udp"
    volumes:
      - /opt/media/bin/www/record:/opt/media/bin/www/record
      - /opt/media/conf:/opt/media/conf
    restart: unless-stopped
